image: "python:3.7-stretch"

stages:
  - test
  - build

pylint:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pylint
    - ci/pylint_runner.sh
  allow_failure: true

pyinstaller:
  stage: build
  only:
    - master
    - develop
  script:
    - pip install -r requirements.txt
    - pip install pyinstaller
    - pyinstaller game.py -p . -F
  artifacts:
    paths:
      - dist
    expire_in: 1 week