image: "python:3.7"

stages:
  - setup
  - test

py-pip:
  stage: setup
  script:
    - python -m pip install -r requirements.txt
    - python -m pip install pylint

pylint:
  stage: test
  script:
    - ci/pylint_runner.sh