image: "python:3.7-stretch"

stages:
  - test
  - build_elf
  - build_deb

pylint:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pylint
    - ci/pylint_runner.sh
  allow_failure: true

tests:
  stage: test
  only:
    - master
    - develop
    - feature/ci
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - ci/tests_runner.sh
  artifacts:
    paths:
      - report.txt
    expire_in: 1 week

pyinstaller:
  stage: build_elf
  only:
    - master
    - develop
    - feature/ci
  script:
    - pip install -r requirements.txt
    - pip install pyinstaller
    - ci/build_elf.sh
  artifacts:
    paths:
      - dist
    expire_in: 1 week

deb-build:
  stage: build_deb
  only:
    - master
    - develop
    - feature/ci
  dependencies:
    - pyinstaller
  script:
    - cd dist
    - mkdir -p DEBIAN
    - mkdir -p usr/bin
    - cp space_caravan usr/bin/